# Generated by Django 5.2.3 on 2025-07-04 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=36)),
                ('apellido', models.CharField(max_length=36)),
                ('password', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=18, unique=True)),
                ('edad', models.IntegerField()),
                ('email', models.EmailField(max_length=45, unique=True)),
                ('celular', models.CharField(max_length=20, unique=True)),
                ('nro_socio', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=36)),
                ('apellido', models.CharField(max_length=36)),
                ('password', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=18, unique=True)),
                ('email', models.EmailField(max_length=45, unique=True)),
                ('legajo', models.IntegerField(unique=True)),
                ('sueldo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Servicio', to='api.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora', models.TimeField()),
                ('fecha', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_turno', to='api.cliente')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empleado_turno', to='api.empleado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_turno', to='api.producto')),
            ],
        ),
    ]
